### ISSUE TITLE
Compass item loss

### ISSUE THREAD

**Issue by Europia79** [Europia79/Demolition#7]
> If a player has a compass in their inventory when they join the game, they lose their compass when they leave.

**Comment by tara81** [comment]
I thought you said you added a compass thing in the config but I don't see it =)

**Comment by Europia79** [comment]
https://github.com/Europia79/Demolition/commit/1fe5b487563ac8db73ca85a7db6125a533433ed7

https://github.com/Europia79/Demolition/blob/master/src/main/java/mc/euro/demolition/BombPlugin.java#L119-L125
https://github.com/Europia79/Demolition/blob/master/src/main/java/mc/euro/demolition/BombPlugin.java#L476-L569

Thanks for letting me know. It's fixed in the new version v1.2.5.1
http://rainbowcraft.sytes.net/download/plugins/BombArena/v1.2.5.1/

https://github.com/Europia79/Demolition/blob/master/src/main/java/mc/euro/demolition/commands/EodExecutor.java#L210
```/bomb reloadconfig```
Also, your other issue with editing the ```config.yml``` should be fixed by using this command. After you edit ```config.yml``` use that command so that Bukkit & BombArena will read the new changes into memory.

Unfortunately, this is an inconvenience caused by the way Bukkit API handles configs: It keeps the master copy in memory and it ignores the changes you make to the actual file on disk.
