### ISSUE TITLE
Configuration doesn't like Bomb Block change.

### ISSUE THREAD

**Issue by tara81** [Europia79/Demolition#8]
I set it to 
BombBlock: REDSTONE_BLOCK 
and it keeps turning back into 
BombBlock: TNT

**Comment by tara81** [comment]
I realized i posted this before, lol.

Well heres my setup
[BattleArena.zip](https://github.com/Europia79/Demolition/files/225827/BattleArena.zip)
[BombArena.zip](https://github.com/Europia79/Demolition/files/225828/BombArena.zip)

**Comment by Europia79** [comment]
https://github.com/Europia79/Demolition/issues/2

This issue was already reported.

**Comment by Europia79** [comment]
hold a ```REDSOTNE_BLOCK``` in your hand, then run the command

```
/bomb setconfig bombblock
```
