### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by tara81** [Europia79/Demolition#9]
Not sure what it's doing

http://pastebin.com/FuVsJtk2

**Comment by Europia79** [comment]
What version of BombArena ?

**Comment by Europia79** [comment]
Can i see your entire server log ?

**Comment by Europia79** [comment]
you're using v1.2.2.1 or v1.2.2 ?

it looks like you left the arena before it started ?

**Comment by Europia79** [comment]
it's fixed in both BattleArena & BombArena

**Comment by tara81** [comment]
v1.2.4 How is it fixeD? it still happens to me .. I left the arena while it was in progress..

**Comment by tara81** [comment]
http://pastebin.com/uEQQDDp0

**Comment by tara81** [comment]
it also happens when I leave other battlearena minigames..

**Comment by Europia79** [comment]
i haven't released the updated version yet.

**Comment by Europia79** [comment]
http://rainbowcraft.sytes.net/download/plugins/BombArena/v1.2.5/

Test that out

**Comment by tara81** [comment]
Thank you. How can I donate to you ?

**Comment by Europia79** [comment]
I don't actually have that setup. It's cool tho. It was fun, plus you helped me out a lot by reporting the errors. Thankyou !
